export default {
  FORBIDDEN: 'FORBIDDEN',
  ROUTE_LOGIN: 'LOGIN',
  ROUTE_MAIN: 'MAIN',
  ROUTE_CLASSES: 'CLASSES',
  ROUTE_STUDENTS: 'STUDENTS',

  GET_ME_REQUEST: 'GET_ME_REQUEST',
  GET_ME_SUCCESS: 'GET_ME_SUCCESS',
  GET_ME_FAILURE: 'GET_ME_FAILURE',

  GET_STUDENTS_REQUEST: 'GET_STUDENTS_REQUEST',
  GET_STUDENTS_SUCCESS: 'GET_STUDENTS_SUCCESS',
  GET_STUDENTS_FAILURE: 'GET_STUDENTS_FAILURE',

  GET_TEACHERS_REQUEST: 'GET_TEACHERS_REQUEST',
  GET_TEACHERS_SUCCESS: 'GET_TEACHERS_SUCCESS',
  GET_TEACHERS_FAILURE: 'GET_TEACHERS_FAILURE',

  GET_CLASSES_REQUEST: 'GET_CLASSES_REQUEST',
  GET_CLASSES_SUCCESS: 'GET_CLASSES_SUCCESS',
  GET_CLASSES_FAILURE: 'GET_CLASSES_FAILURE',

  GET_SUBJECTS_REQUEST: 'GET_SUBJECTS_REQUEST',
  GET_SUBJECTS_SUCCESS: 'GET_SUBJECTS_SUCCESS',
  GET_SUBJECTS_FAILURE: 'GET_SUBJECTS_FAILURE',

  GET_MARKS_REQUEST: 'GET_MARKS_REQUEST',
  GET_MARKS_SUCCESS: 'GET_MARKS_SUCCESS',
  GET_MARKS_FAILURE: 'GET_MARKS_FAILURE',
  POST_MARKS_REQUEST: 'POST_MARKS_REQUEST',
  POST_MARKS_SUCCESS: 'POST_MARKS_SUCCESS',
  POST_MARKS_FAILURE: 'POST_MARKS_FAILURE',
  PUT_MARKS_REQUEST: 'PUT_MARKS_REQUEST',
  PUT_MARKS_SUCCESS: 'PUT_MARKS_SUCCESS',
  PUT_MARKS_FAILURE: 'PUT_MARKS_FAILURE'
}
